=== Dynamensions/Easy-Video-Converter/Dynamensions.EasyVideoConverter/Dynamensions.EasyVideoConverter/Profiles/Schema/profile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Root element -->
	<xs:element name="ClientProfile">
		<xs:complexType>
			<xs:sequence>

				<!-- Direct Play -->
				<xs:element name="DirectPlay" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="VideoCodec" type="xs:string" maxOccurs="unbounded"/>
							<xs:element name="AudioCodec" type="xs:string" maxOccurs="unbounded"/>
							<xs:element name="Container" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<!-- Direct Stream -->
				<xs:element name="DirectStream" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="VideoCodec" type="xs:string" maxOccurs="unbounded"/>
							<xs:element name="AudioCodec" type="xs:string" maxOccurs="unbounded"/>
							<xs:element name="Container" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<!-- Preferred formats -->
				<xs:element name="Preferred" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="VideoCodec" type="xs:string" minOccurs="0"/>
							<xs:element name="AudioCodec" type="xs:string" minOccurs="0"/>
							<xs:element name="Container" type="xs:string" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<!-- Limits -->
				<xs:element name="Limits" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="MaxWidth" type="xs:int" minOccurs="0"/>
							<xs:element name="MaxHeight" type="xs:int" minOccurs="0"/>
							<xs:element name="MaxAudioChannels" type="xs:int" minOccurs="0"/>
							<xs:element name="MaxBitrate" type="xs:int" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<!-- Requirements -->
				<xs:element name="Requirements" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="StrictH264" type="xs:boolean" minOccurs="0"/>
							<xs:element name="Profile" type="xs:string" minOccurs="0"/>
							<xs:element name="Level" type="xs:string" minOccurs="0"/>
							<xs:element name="BitDepth" type="xs:int" minOccurs="0"/>
							<xs:element name="ForceStereoDownmix" type="xs:boolean" minOccurs="0"/>
							<xs:element name="RequiresAacStereoFallback" type="xs:boolean" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<!-- Subtitle capabilities -->
				<xs:element name="Subtitles" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Internal" type="xs:boolean" minOccurs="0"/>
							<xs:element name="External" type="xs:boolean" minOccurs="0"/>
							<xs:element name="SRT" type="xs:boolean" minOccurs="0"/>
							<xs:element name="PGS" type="xs:boolean" minOccurs="0"/>
							<xs:element name="MovText" type="xs:boolean" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<!-- Description -->
				<xs:element name="Description" type="xs:string" minOccurs="0"/>

			</xs:sequence>
			<!-- Attributes -->
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="family" type="xs:string" use="required"/>
			<xs:attribute name="deviceType" type="deviceType" use="required"/>
			

		</xs:complexType>
	</xs:element>

	<!-- Define the enumeration type as a global simpleType so it can be referenced by attributes -->
	<xs:simpleType name="deviceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Unknown"/>
			<xs:enumeration value="StreamingBox"/>
			<xs:enumeration value="StreamingDongle"/>
			<xs:enumeration value="SmartTV"/>
			<xs:enumeration value="GameConsole"/>
			<xs:enumeration value="PC"/>
			<xs:enumeration value="Mobile"/>
			<xs:enumeration value="Tablet"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== Dynamensions/Easy-Video-Converter/Dynamensions.EasyVideoConverter/Dynamensions.EasyVideoConverter/Profiles/Mobile/android-phone.xml
<ClientProfile name="Android Phone (generalized)" family="Android" deviceType="Mobile"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../schema/profile.xsd">

    <DirectPlay>
        <VideoCodec>h264</VideoCodec>
        <VideoCodec>hevc</VideoCodec>
        <AudioCodec>aac</AudioCodec>
        <AudioCodec>ac3</AudioCodec>
        <Container>mp4</Container>
        <Container>mkv</Container>
    </DirectPlay>

    <DirectStream>
        <VideoCodec>h264</VideoCodec>
        <VideoCodec>hevc</VideoCodec>
        <AudioCodec>aac</AudioCodec>
        <AudioCodec>ac3</AudioCodec>
        <Container>mkv</Container>
        <Container>ts</Container>
    </DirectStream>

    <Preferred>
        <VideoCodec>h264</VideoCodec>
        <AudioCodec>aac</AudioCodec>
        <Container>mp4</Container>
    </Preferred>

    <Limits>
        <MaxWidth>1920</MaxWidth>
        <MaxHeight>1080</MaxHeight>
        <MaxAudioChannels>2</MaxAudioChannels>
    </Limits>

    <Requirements>
        <StrictH264>false</StrictH264>
        <BitDepth>8</BitDepth>
        <ForceStereoDownmix>true</ForceStereoDownmix>
    </Requirements>

    <Subtitles>
        <Internal>true</Internal>
        <External>true</External>
        <SRT>true</SRT>
        <PGS>false</PGS>
        <MovText>true</MovText>
    </Subtitles>

    <Description>Android Phone DirectPlay profile</Description>

</ClientProfile>

=== Dynamensions/Easy-Video-Converter/Dynamensions.EasyVideoConverter/Dynamensions.EasyVideoConverter/Profiles/Apple TV/atv-hd.xml
<ClientProfile name="Apple TV HD" family="Apple TV" deviceType="StreamingBox"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../schema/profile.xsd">

    <DirectPlay>
        <VideoCodec>h264</VideoCodec>
        <AudioCodec>aac</AudioCodec>
        <AudioCodec>ac3</AudioCodec>
        <AudioCodec>eac3</AudioCodec>
        <Container>mp4</Container>
        <Container>mkv</Container>
    </DirectPlay>

    <DirectStream>
        <VideoCodec>h264</VideoCodec>
        <AudioCodec>aac</AudioCodec>
        <AudioCodec>ac3</AudioCodec>
        <AudioCodec>eac3</AudioCodec>
        <Container>mkv</Container>
        <Container>ts</Container>
    </DirectStream>

    <Preferred>
        <VideoCodec>h264</VideoCodec>
        <AudioCodec>eac3</AudioCodec>
        <Container>mkv</Container>
    </Preferred>

    <Limits>
        <MaxWidth>1920</MaxWidth>
        <MaxHeight>1080</MaxHeight>
        <MaxAudioChannels>6</MaxAudioChannels>
    </Limits>

    <Requirements>
        <StrictH264>false</StrictH264>
        <BitDepth>8</BitDepth>
        <ForceStereoDownmix>false</ForceStereoDownmix>
    </Requirements>

    <Subtitles>
        <Internal>true</Internal>
        <External>true</External>
        <SRT>true</SRT>
        <PGS>true</PGS>
        <MovText>true</MovText>
    </Subtitles>

    <Description>Apple TV HD DirectPlay profile</Description>

</ClientProfile>

=== Dynamensions/Easy-Video-Converter/Dynamensions.EasyVideoConverter/Dynamensions.EasyVideoConverter/Profiles/Roku/stick-plus.xml
<ClientProfile name="Roku Stick Plus" family="Roku" deviceType="StreamingDongle"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../schema/profile.xsd">

    <DirectPlay>
        <VideoCodec>h264</VideoCodec>
        <VideoCodec>hevc</VideoCodec>
        <AudioCodec>aac</AudioCodec>
        <AudioCodec>ac3</AudioCodec>
        <AudioCodec>eac3</AudioCodec>
        <Container>mp4</Container>
        <Container>mkv</Container>
    </DirectPlay>

    <DirectStream>
        <VideoCodec>h264</VideoCodec>
        <VideoCodec>hevc</VideoCodec>
        <AudioCodec>aac</AudioCodec>
        <AudioCodec>ac3</AudioCodec>
        <AudioCodec>eac3</AudioCodec>
        <Container>mkv</Container>
        <Container>ts</Container>
    </DirectStream>

    <Preferred>
        <VideoCodec>hevc</VideoCodec>
        <AudioCodec>eac3</AudioCodec>
        <Container>mkv</Container>
    </Preferred>

    <Limits>
        <MaxWidth>3840</MaxWidth>
        <MaxHeight>2160</MaxHeight>
        <MaxAudioChannels>6</MaxAudioChannels>
    </Limits>

    <Requirements>
        <StrictH264>false</StrictH264>
        <BitDepth>8</BitDepth>
        <ForceStereoDownmix>false</ForceStereoDownmix>
        <RequiresAacStereoFallback>true</RequiresAacStereoFallback>
    </Requirements>

    <Subtitles>
        <Internal>true</Internal>
        <External>true</External>
        <SRT>true</SRT>
        <PGS>true</PGS>
        <MovText>false</MovText>
    </Subtitles>

    <Description>Roku Streaming Stick+ DirectPlay profile</Description>

</ClientProfile>

=== Dynamensions/Easy-Video-Converter/Dynamensions.EasyVideoConverter/Dynamensions.EasyVideoConverter/Profiles/Chromecast/chromecast-2nd-gen.xml
<ClientProfile name="Chromecast 2nd Gen (2015)" family="Chromecast" deviceType="StreamingDongle"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../schema/profile.xsd">

    <DirectPlay>
        <VideoCodec>h264</VideoCodec>
        <VideoCodec>vp9</VideoCodec>
        <AudioCodec>aac</AudioCodec>
        <AudioCodec>mp3</AudioCodec>
        <Container>mp4</Container>
        <Container>webm</Container>
        <Container>mkv</Container>
    </DirectPlay>

    <DirectStream>
        <VideoCodec>h264</VideoCodec>
        <VideoCodec>vp9</VideoCodec>
        <AudioCodec>aac</AudioCodec>
        <Container>mkv</Container>
        <Container>ts</Container>
    </DirectStream>

    <Preferred>
        <VideoCodec>vp9</VideoCodec>
        <AudioCodec>aac</AudioCodec>
        <Container>webm</Container>
    </Preferred>

    <Limits>
        <MaxWidth>1920</MaxWidth>
        <MaxHeight>1080</MaxHeight>
        <MaxAudioChannels>2</MaxAudioChannels>
    </Limits>

    <Requirements>
        <StrictH264>false</StrictH264>
        <BitDepth>8</BitDepth>
        <ForceStereoDownmix>true</ForceStereoDownmix>
    </Requirements>

    <Subtitles>
        <Internal>false</Internal>
        <External>true</External>
        <SRT>true</SRT>
        <PGS>false</PGS>
        <MovText>false</MovText>
    </Subtitles>

    <Description>Chromecast 2nd Gen DirectPlay profile</Description>

</ClientProfile>

=== Dynamensions/Easy-Video-Converter/Dynamensions.EasyVideoConverter/Dynamensions.EasyVideoConverter/Profiles/Chromecast/chromecast-1st-gen.xml
<ClientProfile name="Chromecast 1st Gen (2015)" family="Chromecast" deviceType="StreamingDongle"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../schema/profile.xsd">

    <DirectPlay>
        <VideoCodec>h264</VideoCodec>
        <AudioCodec>aac</AudioCodec>
        <AudioCodec>mp3</AudioCodec>
        <Container>mp4</Container>
        <Container>webm</Container>
    </DirectPlay>

    <DirectStream>
        <VideoCodec>h264</VideoCodec>
        <AudioCodec>aac</AudioCodec>
        <Container>ts</Container>
    </DirectStream>

    <Preferred>
        <VideoCodec>h264</VideoCodec>
        <AudioCodec>aac</AudioCodec>
        <Container>mp4</Container>
    </Preferred>

    <Limits>
        <MaxWidth>1280</MaxWidth>
        <MaxHeight>720</MaxHeight>
        <MaxAudioChannels>2</MaxAudioChannels>
    </Limits>

    <Requirements>
        <StrictH264>true</StrictH264>
        <Profile>high</Profile>
        <Level>4.0</Level>
        <BitDepth>8</BitDepth>
        <ForceStereoDownmix>true</ForceStereoDownmix>
    </Requirements>

    <Subtitles>
        <Internal>false</Internal>
        <External>true</External>
        <SRT>true</SRT>
        <PGS>false</PGS>
        <MovText>false</MovText>
    </Subtitles>

    <Description>Chromecast 1st Gen DirectPlay profile</Description>

</ClientProfile>
